# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
      options = ["zfsutils"];
    };

  fileSystems."/nix" =
    { device = "rpool/root/nix";
      fsType = "zfs";
      options = ["zfsutils"];
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
      options = ["zfsutils"];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/3564-67E7";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/641ce894-f4dc-4ced-ada9-4813ea86e408"; }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  networking.hostId = "4441267e";
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/1dd3bc65-70dd-48aa-ad62-fe56b63a1c04";
  boot.zfs.devNodes = "/dev/mapper/cryptroot2";
}
